blueprint:
  name: Chauffage intelligent par pièce (multi-entités)
  description: >
    Gestion intelligente du chauffage basée sur présence,
    lumières et ouvertures multiples.
    Support mode température ou preset.
  domain: automation

  input:
    room_name:
      name: Nom de la pièce
      default: Pièce
      selector:
        text:

    presence:
      name: Capteur de présence
      selector:
        entity:
          domain: binary_sensor

    lights:
      name: Lumières de la pièce
      selector:
        entity:
          domain: light
          multiple: true

    windows:
      name: Capteurs d'ouverture
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    climate:
      name: Chauffage (climate)
      selector:
        entity:
          domain: climate

    # ───── Délais ─────
    delay_presence_absent:
      name: Délai absence prolongée
      default: "24:00:00"
      selector:
        duration:

    delay_light_off:
      name: Délai lumière éteinte
      default: "01:30:00"
      selector:
        duration:

    delay_window_open:
      name: Délai fenêtre ouverte
      default: "00:10:00"
      selector:
        duration:

    # ───── Mode de contrôle ─────
    control_mode:
      name: Mode de contrôle
      default: temperature
      selector:
        select:
          options:
            - temperature
            - preset

    # ───── Températures ─────
    temp_comfort:
      name: Température confort
      default: 22
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    temp_eco:
      name: Température éco
      default: 18
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    temp_away:
      name: Température absence
      default: 20
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    # ───── Presets ─────
    preset_comfort:
      name: Preset confort
      default: comfort
      selector:
        text:

    preset_eco:
      name: Preset éco
      default: eco
      selector:
        text:

    preset_away:
      name: Preset absence
      default: away
      selector:
        text:

mode: restart

trigger:

  # Présence ON
  - platform: state
    entity_id: !input presence
    to: "on"
    id: presence_on

  # Présence OFF long
  - platform: state
    entity_id: !input presence
    to: "off"
    for: !input delay_presence_absent
    id: presence_off_long

  # Lumières ON (une quelconque)
  - platform: state
    entity_id: !input lights
    to: "on"
    id: light_on

  # Lumières OFF long (toutes éteintes)
  - platform: state
    entity_id: !input lights
    to: "off"
    for: !input delay_light_off
    id: light_off_long

  # Fenêtre ouverte longtemps (une quelconque)
  - platform: state
    entity_id: !input windows
    to: "on"
    for: !input delay_window_open
    id: window_open_long

  # Fenêtre fermée
  - platform: state
    entity_id: !input windows
    to: "off"
    id: window_closed

action:
  - choose:

      # ───── CONFORT ─────
      - conditions:
          - condition: trigger
            id:
              - presence_on
              - light_on
              - window_closed
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ control_mode == 'temperature' }}"
                sequence:
                  - service: climate.set_temperature
                    target:
                      entity_id: !input climate
                    data:
                      temperature: !input temp_comfort
                      hvac_mode: heat

              - conditions:
                  - condition: template
                    value_template: "{{ control_mode == 'preset' }}"
                sequence:
                  - service: climate.set_preset_mode
                    target:
                      entity_id: !input climate
                    data:
                      preset_mode: !input preset_comfort

      # ───── ECO ─────
      - conditions:
          - condition: trigger
            id: window_open_long
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ control_mode == 'temperature' }}"
                sequence:
                  - service: climate.set_temperature
                    target:
                      entity_id: !input climate
                    data:
                      temperature: !input temp_eco

              - conditions:
                  - condition: template
                    value_template: "{{ control_mode == 'preset' }}"
                sequence:
                  - service: climate.set_preset_mode
                    target:
                      entity_id: !input climate
                    data:
                      preset_mode: !input preset_eco

      # ───── ABSENT ─────
      - conditions:
          - condition: trigger
            id:
              - presence_off_long
              - light_off_long
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ control_mode == 'temperature' }}"
                sequence:
                  - service: climate.set_temperature
                    target:
                      entity_id: !input climate
                    data:
                      temperature: !input temp_away

              - conditions:
                  - condition: template
                    value_template: "{{ control_mode == 'preset' }}"
                sequence:
                  - service: climate.set_preset_mode
                    target:
                      entity_id: !input climate
                    data:
                      preset_mode: !input preset_away
